export default {
  english: {
    popular: [{ label: 'ˈpɑːpjəlɚ', value: 'ˈpɑːpjəlɚ' }],
    bubble: [{ label: 'ˈbʌbəl', value: 'ˈbʌbəl' }],
    tinker: [{ label: 'ˈtɪŋkɚ', value: 'ˈtɪŋkɚ' }],
    dog: [{ label: 'ˈdɑːg', value: 'ˈdɑːg' }],
    crown: [{ label: 'ˈkɹaʊn', value: 'ˈkɹaʊn' }],
    gravely: [{ label: 'ˈgɹeɪˌvliː', value: 'ˈgɹeɪˌvliː' }],
    mapping: [{ label: 'ˈmæpəŋ', value: 'ˈmæpəŋ' }],
    nine: [{ label: 'ˈnaɪn', value: 'ˈnaɪn' }],
    bank: [{ label: 'ˈbæŋk', value: 'ˈbæŋk' }],
    frog: [{ label: 'ˈfɹɑːg', value: 'ˈfɹɑːg' }],
    valve: [{ label: 'ˈvælv', value: 'ˈvælv' }],
    massage: [{ label: 'məˈsɑːʒ', value: 'məˈsɑːʒ' }],
    zoom: [{ label: 'ˈzuːm', value: 'ˈzuːm' }],
    thigh: [{ label: 'ˈθaɪ', value: 'ˈθaɪ' }],
    mother: [{ label: 'ˈmʌðɚ', value: 'ˈmʌðɚ' }],
    shopping: [{ label: 'ˈʃɑːpəŋ', value: 'ˈʃɑːpəŋ' }],
    leisure: [{ label: 'ˈliːʒɚ', value: 'ˈliːʒɚ' }],
    mahogany: [{ label: 'məˈhɑːgəˌniː', value: 'məˈhɑːgəˌniː' }],
    lately: [{ label: 'ˈleɪtˌliː', value: 'ˈleɪtˌliː' }],
    roaring: [{ label: 'ˈɹɔːɹəŋ', value: 'ˈɹɔːɹəŋ' }],
    changed: [{ label: 'ˈʧeɪnʤd', value: 'ˈʧeɪnʤd' }],
    magenta: [{ label: 'məˈʤɛntə', value: 'məˈʤɛntə' }],
    younger: [{ label: 'ˈjʌŋgɚ', value: 'ˈjʌŋgɚ' }],
    whirlwind: [{ label: 'ˈwɚlˌwɪnd', value: 'ˈwɚlˌwɪnd' }],
    cat: [{ label: 'ˈkæt', value: 'ˈkæt' }],
    cot: [{ label: 'ˈkɑːt', value: 'ˈkɑːt' }],
    again: [{ label: 'əˈgɛn', value: 'əˈgɛn' }],
    bird: [{ label: 'ˈbɚd', value: 'ˈbɚd' }],
    bed: [{ label: 'ˈbɛd', value: 'ˈbɛd' }],
    kit: [{ label: 'ˈkɪt', value: 'ˈkɪt' }],
    unique: [{ label: 'ˌjuːˈniːk', value: 'ˌjuːˈniːk' }],
    more: [{ label: 'ˈmɔːɹ', value: 'ˈmɔːɹ' }],
    could: [{ label: 'ˈkʊd', value: 'ˈkʊd' }],
    school: [{ label: 'ˈskuːl', value: 'ˈskuːl' }],
    pulse: [{ label: 'ˈpʌls', value: 'ˈpʌls' }],
    price: [{ label: 'ˈpɹaɪs', value: 'ˈpɹaɪs' }],
    flower: [{ label: 'ˈflaʊɚ', value: 'ˈflaʊɚ' }],
    shade: [{ label: 'ˈʃeɪd', value: 'ˈʃeɪd' }],
    choice: [{ label: 'ˈʧɔɪs', value: 'ˈʧɔɪs' }],
    boat: [{ label: 'ˈboʊt', value: 'ˈboʊt' }],
  },
  audio: [
    {
      label: '打鼓背景音',
      value: 'https://gcore.jsdelivr.net/gh/mekumiao/img-hosting/upload/1415_dhol-drums-01.wav',
      scene: '',
      style: '',
      menuKey: 'default',
    },
    {
      label: '拨号背景音',
      value: 'https://gcore.jsdelivr.net/gh/mekumiao/img-hosting/upload/1378_dial-up-modem-01.wav',
      scene: '',
      style: '',
      menuKey: 'default',
    },
    {
      label: '咕噜咕噜音效',
      value: 'https://gcore.jsdelivr.net/gh/mekumiao/img-hosting/upload/1814_water-bubbles-01.wav',
      scene: '',
      style: '',
      menuKey: 'default',
    },
  ],
  speaker: {
    gender: [
      { label: '男声', value: '男' },
      { label: '女声', value: '女' },
    ],
    category: [
      { label: '热榜', value: '热榜' },
      { label: 'SVIP', value: 'SVIP' },
      { label: '付费', value: '付费' },
    ],
    tags: [
      { label: '影视', value: '影视' },
      { label: '情感', value: '情感' },
      { label: '娱乐', value: '娱乐' },
      { label: '广告', value: '广告' },
      { label: '纪录片', value: '纪录片' },
      { label: '宣传片', value: '宣传片' },
    ],
    children: [
      {
        gender: '女,男',
        isSupport24k: true,
        isStar: true,
        category: '热榜,SVIP,付费',
        tags: ['影视', '情感'],
        name: 'zh-CN-XiaomoNeural',
        remark: 'Xiaomo-晓墨',
        styles: [
          {
            name: 'embarrassed',
            remark: '尴尬',
          },
          {
            name: 'calm',
            remark: '冷静',
          },
          {
            name: 'serious',
            remark: '严肃',
          },
        ],
        roles: [
          {
            name: 'YoungAdultFemale',
            remark: '女青年',
          },
          {
            name: 'YoungAdultMale',
            remark: '男青年',
          },
          {
            name: 'Boy',
            remark: '男孩',
          },
        ],
      },
    ],
  },
}
